### ISSUE TITLE
IllegalArgumentException: Invalid 's' value, should be >= 1 but got 0

### ISSUE THREAD

**Issue by 5chdn** [PegaSysEng/pantheon#239]
### Description
As a Clique Validator, I want to seal blocks so that I can run a PoA chain. 

### Acceptance Criteria
* Pantheon should be able to seal blocks

### Steps to Reproduce (Bug)
1. Checkout master @ ef49f9b3e85dc31db8a6a89111cada4a0613b6a5
2. Run a clique validator node with the following genesis: https://github.com/goerli/testnet/blob/94cee61c55097f3f3dd2ad1b2911e398ad476d1a/geth/goerli.genesis
3. Throw exceptions

**Expected behavior:** 
Start sealing blocks

**Actual behavior:** 
Throws exception

```
2018-11-04 22:07:04.888+01:00 | pool-4-thread-1 | ERROR | BlockMiner | Blocking mining threw an exception {}
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Invalid 's' value, should be >= 1 but got 0
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[guava-23.6-jre.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[guava-23.6-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4864) ~[guava-23.6-jre.jar:?]
	at tech.pegasys.pantheon.consensus.clique.VoteTallyCache.getVoteTallyAtBlock(VoteTallyCache.java:54) ~[pantheon-clique-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.consensus.clique.CliqueHelpers.addressIsAllowedToProduceNextBlock(CliqueHelpers.java:41) ~[pantheon-clique-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.consensus.clique.blockcreation.CliqueBlockMiner.mineBlock(CliqueBlockMiner.java:44) ~[pantheon-clique-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.blockcreation.BlockMiner.run(BlockMiner.java:71) [pantheon-blockcreation-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.IllegalArgumentException: Invalid 's' value, should be >= 1 but got 0
	at tech.pegasys.pantheon.crypto.SECP256K1$Signature.checkInBounds(SECP256K1.java:628) ~[pantheon-crypto-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.crypto.SECP256K1$Signature.create(SECP256K1.java:617) ~[pantheon-crypto-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.crypto.SECP256K1$Signature.decode(SECP256K1.java:644) ~[pantheon-crypto-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.consensus.clique.CliqueExtraData.parseProposerSeal(CliqueExtraData.java:78) ~[pantheon-clique-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.consensus.clique.CliqueExtraData.decode(CliqueExtraData.java:72) ~[pantheon-clique-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.consensus.clique.VoteTallyCache.findMostRecentAvailableVoteTally(VoteTallyCache.java:87) ~[pantheon-clique-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.consensus.clique.VoteTallyCache.populateCacheUptoAndIncluding(VoteTallyCache.java:66) ~[pantheon-clique-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.consensus.clique.VoteTallyCache.lambda$getVoteTallyAtBlock$0(VoteTallyCache.java:54) ~[pantheon-clique-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4869) ~[guava-23.6-jre.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3523) ~[guava-23.6-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2249) ~[guava-23.6-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2132) ~[guava-23.6-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[guava-23.6-jre.jar:?]
	... 9 more
```

**Frequency:** 
100%

### Versions (Add all that apply)
* Software version: master @ ef49f9b3e85dc31db8a6a89111cada4a0613b6a5
* Java version: openjdk version "10.0.2" 2018-07-17
* OS Name & Version: DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
* Kernel Version: Linux eros 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rain-on** [comment]
It looks like the Proposer Seal is not all zeros in the genesis file.
Not sure what geth/parity is expecting, but at the moment, Pantheon expects the proposer seal in the genesis file to be 65 bytes, all zeros.
The genesis file is use has a proposer seal of 0x20794fd02933f303fba550bd1fe2f0649e3576eb000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 - which decodes as an illegal signature,

**Comment by rain-on** [comment]
Looking into this more, it appears the extra data field in the genesis file doesn't conform with Pantheon's expectations in the following ways:
1. There appears to be 65 characters of vanity data (not 64 chars (or 32 bytes))
2. There is insufficient '0' padding to ensure the signature is identified as being 'all zeros'

A valid extra data string could appear (with the same validators) as:
0x2249276d20646f6e652077616974696e672e2e2e20666f7220626c6f636b206696e616c69747922202d20496767792700000000001fa1804c408085d9c57eeb167ce953c99b6cb1e20794fd02933f303fba550bd1fe2f0649e3576eb0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

NOTE: The trailing '6' of the vanity data was removed to ensure the correct length.

**Comment by rain-on** [comment]
As a test, we used the supplied goerli genesis file with the Geth client.
Geth accepted the file, however, only reported 2 clique signers on block 0.
["0x01fa1804c408085d9c57eeb167ce953c99b6cb1e", "0x696e616c69747922202d20496767792700000000"]
This seems to indicate the same issue as we've seen in Pantheon - i.e. an extra trailing "6" in the vanity data string (on the assumption that the validators should match those listed in the parity goerli.json file).

**Comment by rain-on** [comment]
The problem could also be solved by right-padding the extra-data string with sufficient zeros, such that there are 130 trailing 0's in total.
The nice thing about this, is the hex string would then still start with '"I'm done waiting... for block finality" - Iggy'

The validators in that case would appear as:
0 = {Address@3981} "0x696e616c69747922202d20496767792700000000"
1 = {Address@3982} "0x01fa1804c408085d9c57eeb167ce953c99b6cb1e"
2 = {Address@3983} "0x20794fd02933f303fba550bd1fe2f0649e3576eb"

**Comment by 5chdn** [comment]
Thanks, the insufficient 0 padding was indeed the issue. Fixed it now, and it works. Thanks :+1: 

removing the '6' breaks the vanity data by the way, what do you mean by removing the trailing 6?

**Comment by 5chdn** [comment]
Ah gotcha, let me double-check that
