### ISSUE TITLE
CompressionException: Snappy decompression failed

### ISSUE THREAD

**Issue by 5chdn** [PegaSysEng/pantheon#251]
### Description
As a Node Operator, I want ... whatever :laughing:  

### Acceptance Criteria
* Connect to other peers than Pantheon

### Steps to Reproduce (Bug)
1. Checkout latest master @ 5566eb36d83c7323ef27444a2c119dd707fea2e5
2. Connect to Görli https://github.com/goerli/testnet
3. See it fails with `CompressionException` and disconnects any peer that is not Pantheon

**Expected behavior:** 
Sync the network with all peers

**Actual behavior:**
My pantheon nodes connect to each other but not with parity or geth

**Frequency:**
100%

### Versions (Add all that apply)
```
rando@qa-afri-test-v01fa3:~/panth$ git log -n1 | head -n3
commit 5566eb36d83c7323ef27444a2c119dd707fea2e5
Author: Adrian Sutton <adrian@symphonious.net>
Date:   Mon Nov 12 12:42:20 2018 +1000
rando@qa-afri-test-v01fa3:~/panth$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
rando@qa-afri-test-v01fa3:~/panth$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
rando@qa-afri-test-v01fa3:~/panth$ uname -a
Linux qa-afri-test-v01fa3 4.15.0-1030-azure #31~16.04.1-Ubuntu SMP Tue Oct 30 19:40:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
### Additional Information

```
6|panth  | 2018-11-12 09:56:06.672+00:00 | nioEventLoopGroup-3-1 | INFO  | WaitForPeerTask | Waiting for new peer connection. 5 peers currently connected, Some peers idle.
6|panth  | 2018-11-12 09:56:06.672+00:00 | nioEventLoopGroup-3-1 | INFO  | WaitForPeerTask | Finished waiting for peer connection.
6|panth  | 2018-11-12 09:56:06.672+00:00 | nioEventLoopGroup-3-1 | INFO  | Downloader | Caught up to best peer: 0
6|panth  | 2018-11-12 09:56:06.672+00:00 | nioEventLoopGroup-3-1 | INFO  | WaitForPeerTask | Waiting for new peer connection. 5 peers currently connected, Some peers idle.
6|panth  | 2018-11-12 09:56:06.711+00:00 | nioEventLoopGroup-3-1 | ERROR | DeFramer | Exception while processing incoming message
6|panth  | io.netty.handler.codec.DecoderException: tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.CompressionException: Snappy decompression failed
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.netty.AbstractHandshakeHandler.channelRead0(AbstractHandshakeHandler.java:119) [pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.netty.AbstractHandshakeHandler.channelRead0(AbstractHandshakeHandler.java:39) [pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
6|panth  | Caused by: tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.CompressionException: Snappy decompression failed
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.SnappyCompressor.decompress(SnappyCompressor.java:44) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.Framer.processFrame(Framer.java:265) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.Framer.deframe(Framer.java:156) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.netty.DeFramer.decode(DeFramer.java:67) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	... 22 more
6|panth  | Caused by: java.io.IOException: FAILED_TO_UNCOMPRESS(5)
6|panth  | 	at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:98) ~[snappy-java-1.1.7.1.jar:1.1.7.1]
6|panth  | 	at org.xerial.snappy.SnappyNative.rawUncompress(Native Method) ~[snappy-java-1.1.7.1.jar:1.1.7.1]
6|panth  | 	at org.xerial.snappy.Snappy.rawUncompress(Snappy.java:474) ~[snappy-java-1.1.7.1.jar:1.1.7.1]
6|panth  | 	at org.xerial.snappy.Snappy.uncompress(Snappy.java:513) ~[snappy-java-1.1.7.1.jar:1.1.7.1]
6|panth  | 	at org.xerial.snappy.Snappy.uncompress(Snappy.java:488) ~[snappy-java-1.1.7.1.jar:1.1.7.1]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.SnappyCompressor.decompress(SnappyCompressor.java:42) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.Framer.processFrame(Framer.java:265) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.Framer.deframe(Framer.java:156) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.netty.DeFramer.decode(DeFramer.java:67) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	... 22 more
6|panth  | 2018-11-12 09:56:06.937+00:00 | nioEventLoopGroup-3-1 | ERROR | DeFramer | Exception while processing incoming message
6|panth  | io.netty.handler.codec.DecoderException: tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.FramingException: Frame MAC did not match expected MAC; expected: 6de1c2f6aee7072e8daced1e37d2a66c, received: a9ee9463d77e19fc1e59146a37c70f94
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:763) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
6|panth  | Caused by: tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.FramingException: Frame MAC did not match expected MAC; expected: 6de1c2f6aee7072e8daced1e37d2a66c, received: a9ee9463d77e19fc1e59146a37c70f94
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.Framer.error(Framer.java:376) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.Framer.validateMac(Framer.java:280) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.Framer.processFrame(Framer.java:247) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.rlpx.framing.Framer.deframe(Framer.java:156) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at tech.pegasys.pantheon.ethereum.p2p.netty.DeFramer.decode(DeFramer.java:67) ~[pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.15.Final.jar:4.1.15.Final]
6|panth  | 	... 17 more
6|panth  | 2018-11-12 09:56:11.673+00:00 | EthSchedulerTimer | INFO  | Downloader | Caught up to best peer: 0
6|panth  | 2018-11-12 09:56:11.674+00:00 | EthSchedulerTimer | INFO  | WaitForPeerTask | Waiting for new peer connection. 4 peers currently connected, Some peers idle.
6|panth  | 2018-11-12 09:56:16.675+00:00 | EthSchedulerTimer | INFO  | Downloader | Caught up to best peer: 0
6|panth  | 2018-11-12 09:56:16.675+00:00 | EthSchedulerTimer | INFO  | WaitForPeerTask | Waiting for new peer connection. 2 peers currently connected, Some peers idle.
6|panth  | 2018-11-12 09:56:21.676+00:00 | EthSchedulerTimer | INFO  | Downloader | Caught up to best peer: 0
6|panth  | 2018-11-12 09:56:21.676+00:00 | EthSchedulerTimer | INFO  | WaitForPeerTask | Waiting for new peer connection. 3 peers currently connected, Some peers idle.
6|panth  | 2018-11-12 09:56:26.677+00:00 | EthSchedulerTimer | INFO  | Downloader | Caught up to best peer: 0
6|panth  | 2018-11-12 09:56:26.677+00:00 | EthSchedulerTimer | INFO  | WaitForPeerTask | Waiting for new peer connection. 2 peers currently connected, Some peers idle.
6|panth  | 2018-11-12 09:56:31.679+00:00 | EthSchedulerTimer | INFO  | Downloader | Caught up to best peer: 0
6|panth  | 2018-11-12 09:56:31.680+00:00 | EthSchedulerTimer | INFO  | WaitForPeerTask | Waiting for new peer connection. 2 peers currently connected, Some peers idle.
6|panth  | 2018-11-12 09:56:35.115+00:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by timer expiry
```

**Comment by shemnon** [comment]
First pass I am unable to reproduce this on a Mac.  Does this happen all the time on your Azure nodes?  Has it happened anywhere else?

**Comment by ajsutton** [comment]
As discussed on Gitter the reason the Pantheon nodes were not connecting to other nodes was because they were using the default network ID instead of 6284 which is used for Goerli. We still want to track down and fix the snappy decompression failure.

**Comment by ajsutton** [comment]
Managed to capture data for the messages being sent that triggered one of these errors.  It appears that we're getting a HELLO message indicating devp2p version 5 so Pantheon enables compression but the next message we get is a DISCONNECT with reason TIMEOUT which isn't compressed.

My guess is that the remote peer timed out waiting for our HELLO message so sent the disconnect - because it hasn't received HELLO it wouldn't have enabled compression.  The only other sane option would be to just terminate the connection without sending a DISCONNECT message. The remote client happens to be Parity (`Parity/v1.10.6-stable-bc0d134-20180605/x86_64-linux-gnu/rustc1.26.1`) so I'm fairly inclined to take it's behaviour as the "right" answer. :)

But I also don't think Pantheon should be trying to detect if the messages are unencrypted on devp2p - we should just disconnect for breach of protocol without the big noisy error.  @5chdn Does that seem reasonable to you?
