### ISSUE TITLE
A lot of peering issues

### ISSUE THREAD

**Issue by 5chdn** [PegaSysEng/pantheon#286]
Version: master @ c5559936482837a8c6afb82ca537862aa240c290

```
❯ ./pantheon --genesis=/home/user/.opt/testnet/geth/goerli.genesis --rpc-enabled --datadir=/tmp/goerli/pantheon --bootnodes=enode://6b0f579c20bbb82bb84c439b409c52aed2b86df135ffdf14139238bdf364817cefd827217e294dc4f38f4ed965ac26be34bfaca0ebfd30fdf502f91511a7c716@192.168.43.132:30312,enode://ac1977d8753fc12dd801e87139c0fd56fed3bac136c8a9cafe4f82e147612f3232266e7f4c74d869722fd26ecefff42496ea7b2225d624d432c123f5f4ed44b8@192.168.43.132:30403,enode://3dcc220acdb4409838482f98cd822a67470077746319725c2b0e28713a8790b7a82ad7fbb64c98564eac428169fc3ea35a2749c783164cad39fc78fef05ad29e@127.0.0.1:30303,enode://04fb7acb86f47b64298374b5ccb3c2959f1e5e9362158e50e0793c261518ffe83759d8295ca4a88091d4726d5f85e6276d53ae9ef4f35b8c4c0cc6b99c8c0537@40.70.214.166:40303,enode://17de5580bbc1620081a21f82954731c7854305463630a0d677ed991487609829a6bf1ffcb8fb8ef269eff4829690625db176b498c629b9b13cb39b73b6e7b08b@213.186.16.82:1345,enode://22da3ef3707626a92a32b0527d0846f88228daa0536c62d83c9ac7e96660bc8e4ac70a9aa8f8cedf71b580cd41449ad46c6e5a06ecf138b142f38a9d1b2b856a@85.7.110.224:30303,enode://3897b1a5786948f643d9755df92dc56d0b2284f36730dc198ef371aebf191b24b5cbe8162c2032b09b2f14ba73460bfc3f7d4ef1e26bcc59297d4f235dc5cdc5@54.88.169.219:30303,enode://3d197d65ed92af6d0adf280ce486714fb641ef9f9f38f0bdd5ddd552666fc1132f033eb249a87f7f30086902c131f30f054f872ae80ac83eea6bd3760a7bbce2@40.70.214.166:30405,enode://3d8d6698d2d4d730d896c7c1e3602ff845343f71bacbf8cb614b0e94fcb3b10e1a49ac2a5063c76617182a1c5928a4a63d4be897e54ae1cb858a1b94d0d275b8@188.166.20.30:30303,enode://46add44b9f13965f7b9875ac6b85f016f341012d84f975377573800a863526f4da19ae2c620ec73d11591fa9510e992ecc03ad0751f53cc02f7c7ed6d55c7291@94.237.54.114:30313,enode://5065d5221b507764771a8b74abc69df0351217eae09b96ec0df4275576a8b2bbba9986ce3037e6fb3c933b5b301364e18030c1ada8cec4ae00f1fa4dfff32eb8@13.113.211.0:30303,enode://573b6607cd59f241e30e4c4943fd50e99e2b6f42f9bd5ca111659d309c06741247f4f1e93843ad3e8c8c18b6e2d94c161b7ef67479b3938780a97134b618b5ce@52.56.136.200:30303,enode://57f58f16fccdd9fb6f587565ac09af4b3b4b33d0fbd14252cc61d29a65b0d83c08419e67ac5292b9342090053526b847f2487278e609f4b4cd1dbf0f48105b2b@213.186.16.82:30303,enode://5d9b1cba03738dfd23e12e4efb99b72623474fece2cc582c95e3ba7d481d519dea0029901f1f844116bab806044e8552f0431b21cf8d96010fc351b483330faa@13.78.10.94:30405,enode://7232e76a13a1abdfd75138f6499c310593d3376eef990de3c86593c85be0c09010f69276bd0f33eb4f9fef7316b9af6fa3fe332878642a813f86f8fdf03a0989@23.233.68.118:30303,enode://7592caf086d4d443905508492f40145bb1a0883ef7cbb9906b613eba6b501806e4ba0545a8e576236408e5b050e752e80a58445fb0ff2699b5ba4e334f481e40@13.78.10.94:30303,enode://76850e0836d0074e060118bf57a627bfd8af3b59871fd16cb4d0ca826eda7a60b0e773f359335e5e3c6cea8a72b1efbf9a298a61b88d0c94ab1a6ea34f1d6c40@13.78.10.94:40303,enode://85e577ec505b70e45ee6556809864c5211a5f10a46149d4caf1c6952fcbbd7f950c9510351f50f14374cd110fdb314f5cf9dcda92b25b82c4f2a1d008f15cf06@80.187.104.237:30303,enode://87a7adc692793eb41918b74b7ba4aa9ec1b45a24917fd6e66118ffc9ffcac9d2672941fc10fd5a2d44e76d02628e273f861bf480311e31babd1ee211f5838e40@168.61.153.244:30405,enode://9b1274fc252261bd9d8687bdc37cc3768551b93c9f3a3b3df2f4c7bbe6d797fb8c2ea6fb398114b2c6c6889a8257c244dfc57c1bb7b578c15cc5cc81fc0b3f79@168.61.153.244:30303,enode://9bc25c32aaed85926a663563c8aa1c9abef6fb18e9282b7ae00584c9ed9ef8e353f18459b591c59b08f5f1ce692cf27cfdc5a0ff85312656aa65552e789f2315@40.74.91.252:40303,enode://9ddf3e1ade168b2eea2d917dc32faffc727d53f488c78b293a523fda880bcca0b072506cf1ee6e743618d43f52e192fadc5ef5b43203a7f8e27b93a299248e3e@40.74.91.252:30405,enode://9e1b905a47caa6f4379c550a91b19df94c633689ee0d5bd4b317b998b052f270b715379fe5d4340fcca19116465443a79adb90883ccfffaf150432b505ccf3fd@159.203.190.82:30312,enode://a899e1b4551eb4d6e906a1313b8ba52e89eeb13412f1da058fd5a0cf261c235cb42fa38cc6c21b0fd5f5bcc5c5daa06945ea0410071cf34468a2f428454682ed@40.70.214.166:30303,enode://ac1977d8753fc12dd801e87139c0fd56fed3bac136c8a9cafe4f82e147612f3232266e7f4c74d869722fd26ecefff42496ea7b2225d624d432c123f5f4ed44b8@80.187.104.212:30303,enode://b0e75e7306435b7986567dafc8d9ca804b09a6f4b68fa1a6a2a5cb9979845b1dfd210c877dadfda0cebaf4ceb111114392df4bd50e223e71de3e807055707f19@86.103.218.43:30308,enode://b1668e8808fe1cd0c518a3ea8090f5412f62dc0cee64dbdec21dc3894aa32838b399e411481f070994e09ce8fddaaaa433bc2f4ad277aa5973080832546df631@123.113.131.26:30300,enode://b16d3bf8d6fe582e4a30698e536247ed9218c0706b890d7120c771fe510e77a79907ec2db2d5a1a393cdcd972eacefc07bebaeb99de5f7b169cb6b90951d1799@213.32.72.208:30303,enode://bc5235d7f37062b9c51108b0178df95b5e1ae9d1e79b950f5e7445ad6d101175d3a72b5e1ea89e459e2a430cc1d997833b8f9fa4637901b77821d96d47d19dcc@46.101.231.8:30303,enode://cbe600c451966737d858d8d561a913bb47770d4e24c50968c0d24b833613afc61daf88a0e1dabde5de01fa9a06469c6daa2bbf0e53dd6485f5b67eb4d3d65ab8@68.183.116.121:30303,enode://d21512d5900be2f67092526411d6d2b45ec50d5b6af33ccf1c519f45aea53662ac33fe36e6f5966d740e6f4f1f5df51462ff496ff8192ef52b9fac0f7bd49de9@213.186.16.82:30303,enode://d686ec8bf4bf0b205e8888e207352e6585232395e998cc1910b33be479c8405352ae1fc56aea79b2482b1b2d89412dc81091aa67ce775e335cd0f7d9dbfdfba3@84.196.20.71:30303,enode://d6acd86efcbb12d18b4287b8695ebc4730e67b1096de826df4bc05392004d66f977cff2844a7ead0a12cad961aa8277b1e032ee2c92ca40b4a2d76dd409da4ac@159.89.119.66:30303,enode://de2b54a19c9d77f94626043e0fea0c0878d5aa8eb1b58afb5bb1ca4fdd91d68e4a13a108a8f1a30009b258eb7f7b35efa71dcbdfda01a9aa0de06bf3898580f9@147.75.62.159:40404,enode://ea26ccaf0867771ba1fec32b3589c0169910cb4917017dba940efbef1d2515ce864f93a9abc846696ebad40c81de7c74d7b2b46794a71de8f95a0d019f494ff3@168.61.153.255:40303,enode://ed70646a024612fa0db4fdb276a3add7ea322b13bec80dd1566186cc86cf9b853e1553eb0f49d3c4b9b37dc936f80e9ee0a2432b7b53f0b0d792fc2cdfb62861@88.19.163.180:30303,enode://efaf6dad7a0773d911a6fcc44939faaba5d4802a7de8514bfacf9cc1ec9c292c82c1741eb4f14010895a273e7c94703cfc10c06068f6daa6ad25d4b0c0ca8e33@40.74.91.252:30303,enode://fede36ae9fb2347204b80e6e81cbe226eb6c6f2052e5fea8e4a224dcd69f3af062ca281064b9001d497f63d85447fef4c48018319654b04f9cd9ce619baedc23@86.103.218.43:30308,enode://04fb7acb86f47b64298374b5ccb3c2959f1e5e9362158e50e0793c261518ffe83759d8295ca4a88091d4726d5f85e6276d53ae9ef4f35b8c4c0cc6b99c8c0537@40.70.214.166:40303,enode://3d197d65ed92af6d0adf280ce486714fb641ef9f9f38f0bdd5ddd552666fc1132f033eb249a87f7f30086902c131f30f054f872ae80ac83eea6bd3760a7bbce2@40.70.214.166:30405,enode://5d9b1cba03738dfd23e12e4efb99b72623474fece2cc582c95e3ba7d481d519dea0029901f1f844116bab806044e8552f0431b21cf8d96010fc351b483330faa@13.78.10.94:30405,enode://7592caf086d4d443905508492f40145bb1a0883ef7cbb9906b613eba6b501806e4ba0545a8e576236408e5b050e752e80a58445fb0ff2699b5ba4e334f481e40@13.78.10.94:30303,enode://76850e0836d0074e060118bf57a627bfd8af3b59871fd16cb4d0ca826eda7a60b0e773f359335e5e3c6cea8a72b1efbf9a298a61b88d0c94ab1a6ea34f1d6c40@13.78.10.94:40303,enode://87a7adc692793eb41918b74b7ba4aa9ec1b45a24917fd6e66118ffc9ffcac9d2672941fc10fd5a2d44e76d02628e273f861bf480311e31babd1ee211f5838e40@168.61.153.244:30405,enode://9b1274fc252261bd9d8687bdc37cc3768551b93c9f3a3b3df2f4c7bbe6d797fb8c2ea6fb398114b2c6c6889a8257c244dfc57c1bb7b578c15cc5cc81fc0b3f79@168.61.153.244:30303,enode://9bc25c32aaed85926a663563c8aa1c9abef6fb18e9282b7ae00584c9ed9ef8e353f18459b591c59b08f5f1ce692cf27cfdc5a0ff85312656aa65552e789f2315@40.74.91.252:40303,enode://9ddf3e1ade168b2eea2d917dc32faffc727d53f488c78b293a523fda880bcca0b072506cf1ee6e743618d43f52e192fadc5ef5b43203a7f8e27b93a299248e3e@40.74.91.252:30405,enode://a899e1b4551eb4d6e906a1313b8ba52e89eeb13412f1da058fd5a0cf261c235cb42fa38cc6c21b0fd5f5bcc5c5daa06945ea0410071cf34468a2f428454682ed@40.70.214.166:30303,enode://ea26ccaf0867771ba1fec32b3589c0169910cb4917017dba940efbef1d2515ce864f93a9abc846696ebad40c81de7c74d7b2b46794a71de8f95a0d019f494ff3@168.61.153.244:40303,enode://efaf6dad7a0773d911a6fcc44939faaba5d4802a7de8514bfacf9cc1ec9c292c82c1741eb4f14010895a273e7c94703cfc10c06068f6daa6ad25d4b0c0ca8e33@40.74.91.252:30303,enode://a72dd7b2f2f30a2e5e1df1fbe116f66ecb278305a8edbc2877b363598d30d8fd0559f1ba20b55db8ce1ff39894bc33e346d91d7b821c2fb3c8c8250d64aa34f5@127.0.0.1:30303,enode://3dcc220acdb4409838482f98cd822a67470077746319725c2b0e28713a8790b7a82ad7fbb64c98564eac428169fc3ea35a2749c783164cad39fc78fef05ad29e@127.0.0.1:30303,enode://ac1977d8753fc12dd801e87139c0fd56fed3bac136c8a9cafe4f82e147612f3232266e7f4c74d869722fd26ecefff42496ea7b2225d624d432c123f5f4ed44b8@127.0.0.1:30403 --p2p-listen=0.0.0.0:30405 --rpc-listen=0.0.0.0:8765

2018-11-20 17:22:40.346+01:00 | main | INFO  | KeyPairUtil | Loaded key 0x7ee21d4b17c84e78a98cf975d3d95464f16e02787f8b3e346037ee5a8f42478a607419012147a36b04bf80879012e072e1fff0dfc087104e91061c76ef9a5de0 from /tmp/goerli/pantheon/key
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/user/.opt/pantheon/build/distributions/pantheon-0.9.0-SNAPSHOT/lib/netty-common-4.1.15.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-11-20 17:22:41.208+01:00 | nioEventLoopGroup-2-1 | INFO  | NettyP2PNetwork | P2PNetwork started and listening on /0:0:0:0:0:0:0:0:30405
2018-11-20 17:22:41.250+01:00 | main | INFO  | Runner | Starting Ethereum main loop ... 
2018-11-20 17:22:41.251+01:00 | main | INFO  | NetworkRunner | Starting Network.
2018-11-20 17:22:41.253+01:00 | main | INFO  | DefaultSynchronizer | Starting synchronizer.
2018-11-20 17:22:41.257+01:00 | main | INFO  | WaitForPeersTask | Waiting for 1 peers to connect.
2018-11-20 17:22:41.257+01:00 | NetworkRunner | INFO  | PeerDiscoveryAgent | Starting peer discovery agent on host=0.0.0.0, port=30405
2018-11-20 17:22:41.261+01:00 | main | INFO  | JsonRpcHttpService | Starting JsonRPC service on 0.0.0.0:8765
2018-11-20 17:22:41.355+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryAgent | Started peer discovery agent successfully, on effective host=0.0.0.0 and port=30405
2018-11-20 17:22:41.527+01:00 | vert.x-eventloop-thread-4 | INFO  | JsonRpcHttpService | JsonRPC service started and listening on 0.0.0.0:8765
2018-11-20 17:22:41.528+01:00 | main | INFO  | Runner | Ethereum main loop is up.
2018-11-20 17:23:11.838+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by timer expiry
2018-11-20 17:23:41.843+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers
2018-11-20 17:24:11.838+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers
2018-11-20 17:24:41.838+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers
```

I can not connect this Pantheon node to any peer. I supply more than 30 bootnodes. A couple of them are even on the same machine. The network is [Görli](https://github.com/goerli/testnet/blob/master/geth/goerli.genesis), the other clients are mainly Geth, Parity, Nethermind, but also other Pantheon nodes: https://stats.goerli.net/

Locally, I run four nodes: Geth, Parity, Pantheon, Nethermind. Pantheon is the only one who cannot connect to any peer provided, the other three clients are well connected. What could it be?

Bonus (unrelated): Disconnecting the Internet kills Pantheon by throwing some exception about resolving addresses, the other clients happily continue syncing blocks even there is no route other than local loop. 

```
2018-11-20 17:32:16.910+01:00 | vert.x-eventloop-thread-1 | WARN  | PeerDiscoveryAgent | Sending to peer DiscoveryPeer{status=bonding, endPoint=Endpoint{host='149.28.115.53', udpPort=1040}, firstDiscovered=1542731387073, lastContacted=1542731485647, lastSeen=0} failed, packet: 0x2ff00c0844b018b40ecaff07d6ccebe96330d73498029971390911e89fadeceaee9736f03bd125319f957278c5fb3666cfa52144d1c7c3ef13c8da53471b8e3d54588fb72f609a9912207e8f985c2b40f27694bede41a11fa23d498b3f0d05520001de04cb84000000008276c58276c5c984951c73358204108086016731f8046b
java.net.SocketException: Network is unreachable
	at sun.nio.ch.DatagramChannelImpl.send0(Native Method) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:584) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:546) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:529) ~[?:?]
	at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:291) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:142) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:875) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:362) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:842) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1321) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1041) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.vertx.core.datagram.impl.DatagramSocketImpl.doSend(DatagramSocketImpl.java:258) [vertx-core-3.5.0.jar:?]
	at io.vertx.core.datagram.impl.DatagramSocketImpl.lambda$send$2(DatagramSocketImpl.java:242) [vertx-core-3.5.0.jar:?]
	at io.vertx.core.impl.AddressResolver.lambda$null$0(AddressResolver.java:89) [vertx-core-3.5.0.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344) [vertx-core-3.5.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.15.Final.jar:4.1.15.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by 5chdn** [comment]
Also, UnsupportedAddressTypeException:

```
2018-11-20 18:49:49.107+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers
2018-11-20 18:50:19.100+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers
2018-11-20 18:50:20.857+01:00 | vert.x-eventloop-thread-1 | WARN  | PeerDiscoveryAgent | Sending to peer DiscoveryPeer{status=bonding, endPoint=Endpoint{host='408b:9f15:607f:0:1000:0:0:0', udpPort=30303, getTcpPort=30303}, firstDiscovered=1542733249328, lastContacted=0, lastSeen=0} failed, packet: 0xae7610b61236e376ee722a60c76e98badcdef14636abec38ccbcce9a82cdc3fb947c213b10756f52b0a25c863f4be8c6821554cbedb4266407061e1532f08a1c2b48e4ac42821444a24f11978bbfe786b0775608ef6198c235eea272eb6a92dc0101ec04cb84000000008276c58276c5d790408b9f15607f0000100000000000000082765f82765f860167323f7d10
java.nio.channels.UnsupportedAddressTypeException: null
	at sun.nio.ch.Net.checkAddress(Net.java:142) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:501) ~[?:?]
	at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:291) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:142) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:875) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:362) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:842) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1321) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1041) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.vertx.core.datagram.impl.DatagramSocketImpl.doSend(DatagramSocketImpl.java:258) [vertx-core-3.5.0.jar:?]
	at io.vertx.core.datagram.impl.DatagramSocketImpl.lambda$send$2(DatagramSocketImpl.java:242) [vertx-core-3.5.0.jar:?]
	at io.vertx.core.impl.AddressResolver.lambda$null$0(AddressResolver.java:89) [vertx-core-3.5.0.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344) [vertx-core-3.5.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.15.Final.jar:4.1.15.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2018-11-20 18:50:49.100+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers
2018-11-20 18:51:19.121+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers
2018-11-20 18:51:20.971+01:00 | vert.x-eventloop-thread-1 | WARN  | PeerDiscoveryAgent | Sending to peer DiscoveryPeer{status=bonding, endPoint=Endpoint{host='408b:9f15:607f:0:1000:0:0:0', udpPort=30303, getTcpPort=30303}, firstDiscovered=1542733249328, lastContacted=0, lastSeen=0} failed, packet: 0xcfadbd4f912460a6366c16b5e8e21e0b6cee03189e4b9a958f9e8c5a3a689718f97c53578eab8b3fe760b380370ecbc7cb7e15aa29b21ae0e8381978c8f3d3aa5fee0f198348a4c02e2c51a9e0efbf8bb843cf14b66b36e0c348e399c72219530101ec04cb84000000008276c58276c5d790408b9f15607f0000100000000000000082765f82765f860167324067dc
java.nio.channels.UnsupportedAddressTypeException: null
	at sun.nio.ch.Net.checkAddress(Net.java:142) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:501) ~[?:?]
	at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:291) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:142) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:875) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:362) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:842) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1321) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1041) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.vertx.core.datagram.impl.DatagramSocketImpl.doSend(DatagramSocketImpl.java:258) [vertx-core-3.5.0.jar:?]
	at io.vertx.core.datagram.impl.DatagramSocketImpl.lambda$send$2(DatagramSocketImpl.java:242) [vertx-core-3.5.0.jar:?]
	at io.vertx.core.impl.AddressResolver.lambda$null$0(AddressResolver.java:89) [vertx-core-3.5.0.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344) [vertx-core-3.5.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.15.Final.jar:4.1.15.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by NicolasMassart** [comment]
Just to be able to reproduce, can you confirm the genesis file is https://github.com/goerli/testnet/blob/master/geth/goerli.genesis ?

**Comment by shemnon** [comment]
For the unsupported address type #281 will fix that.

However that IPv6 address appears to be bogus (https://www.iana.org/assignments/ipv6-address-space/ipv6-address-space.xhtml - 4000::/3 shows as reserved).   Someone is likely fuzzing the Görli network because you will also notice while the address remains the same the nodeid changes regularly.

**Comment by 5chdn** [comment]
@NicolasMassart yes

**Comment by 5chdn** [comment]
launching 4 clients, connecting them to goerli, live:

https://asciinema.org/a/iXnEAHFzy30GZaaqFWzWhYXuy

Note, how pantheon deals with it

**Comment by Errorific** [comment]
Hi @5chdn,
Watching the video it looks like you're missing the argument '--network-id=6284'.
Previously when a network id wasn't provided we used the channel id in it's place, this changed in our recent release.
Let me know how you go.

**Comment by 5chdn** [comment]
Not again -.-

I really suggest you switch to chain specs rather than genesis files. Sorry for the buzz
