### ISSUE TITLE
Support IPv6 link local addresses

### ISSUE THREAD

**Issue by ajsutton** [PegaSysEng/pantheon#288]
### Description
When specifying boot nodes, global unicast IPv6 addresses are now parsed correctly but link local addresses are not.  For example `fe80::8d9:88f5:b6d9:ad54%en0`:

```
$ping6 fe80::8d9:88f5:b6d9:ad54%en0
PING6(56=40+8+8 bytes) fe80::8d9:88f5:b6d9:ad54%en0 --> fe80::8d9:88f5:b6d9:ad54%en0
16 bytes from fe80::8d9:88f5:b6d9:ad54%en0, icmp_seq=0 hlim=64 time=0.100 ms
16 bytes from fe80::8d9:88f5:b6d9:ad54%en0, icmp_seq=1 hlim=64 time=0.096 ms
```

But:

```
$ pantheon --p2p-listen '[fe80::8d9:88f5:b6d9:ad54%en0]:30305'
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (tech.pegasys.pantheon.cli.PantheonCommand@610db97e): java.lang.IllegalArgumentException: valid advertisement host required
	at picocli.CommandLine.execute(CommandLine.java:1051)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
	at tech.pegasys.pantheon.cli.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:59)
	at tech.pegasys.pantheon.cli.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:26)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
	at tech.pegasys.pantheon.cli.PantheonCommand.parse(PantheonCommand.java:412)
	at tech.pegasys.pantheon.Pantheon.main(Pantheon.java:37)
Caused by: java.lang.IllegalArgumentException: valid advertisement host required
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at tech.pegasys.pantheon.ethereum.p2p.discovery.PeerDiscoveryAgent.validateConfiguration(PeerDiscoveryAgent.java:385)
	at tech.pegasys.pantheon.ethereum.p2p.discovery.PeerDiscoveryAgent.<init>(PeerDiscoveryAgent.java:125)
	at tech.pegasys.pantheon.ethereum.p2p.netty.NettyP2PNetwork.<init>(NettyP2PNetwork.java:163)
	at tech.pegasys.pantheon.RunnerBuilder.lambda$build$1(RunnerBuilder.java:142)
	at tech.pegasys.pantheon.ethereum.p2p.NetworkRunner$Builder.build(NetworkRunner.java:182)
	at tech.pegasys.pantheon.RunnerBuilder.build(RunnerBuilder.java:144)
	at tech.pegasys.pantheon.cli.PantheonCommand.synchronize(PantheonCommand.java:507)
	at tech.pegasys.pantheon.cli.PantheonCommand.run(PantheonCommand.java:436)
	at picocli.CommandLine.execute(CommandLine.java:1043)
	... 11 more
```

Pantheon doesn't handle the `%en0` suffix but it's required to make the address route correctly.

**Comment by shemnon** [comment]
I think this goes deeper because only the address bytes of an IPv6 address are encoded into the RLP for pantheon right now, the zone index is dropped (the %en0, %eth0, or %3 part).  All we get are the 16 octets of the address.

It is also problematic because zone indexes differer on each machine, so broadcasting the zone index means nothing on other machines.  And if we receive a link local address we cannot be sure it's on the correct interface and can't just assign it to the inbound interface.

So my inclination is to support link-local only for boot nodes or explicit add-nodes calls and to not propagate them in discovery requests.  We also discard link local addresses on inbound discovery packets.  Hence we support IPv6 link local networks but they must be manually constructed.

My second thought is that nobody is doing this so we should shelve this issue until someone requests it.  I swag it at two days testing integration by hand and non-integration unit tests.

**Comment by ajsutton** [comment]
It is possible to use the full IPv6 link local address to communicate between machines on the same local network and the zone index is required to achieve that (it identifies the interface on the target machine so doesn't change).  However, since we can't embed the zone index in the discovery packets it's not going to work as the link local address without the zone index is not sufficient.

As such, I'm going to close this as a won't fix until either devp2p discovery standards are updated to support it or Pantheon supports some other p2p network which can work with link local IPv6.
