### ISSUE TITLE
NullPointerException When Starting Node

### ISSUE THREAD

**Issue by etscrivner** [PegaSysEng/pantheon#854]
### Description
While attempt to run Pantheon 0.9.1 as follows:

```
pantheon --config-file=/app/config.toml
```

With the following configuration TOML:

```toml
data-path="/data"
network="ROPSTEN"
rpc-http-enabled=true
rpc-http-port=5432
logging="DEBUG"
```

I received the following exception from the application:

```
picocli.CommandLine$ExecutionException: Error while running command (tech.pegasys.pantheon.cli.PantheonCommand@49c6c24f): java.lang.NullPointerException
 	at picocli.CommandLine.execute(CommandLine.java:1168)
 	at picocli.CommandLine.access$800(CommandLine.java:141)
 	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
 	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
 	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
 	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
 	at tech.pegasys.pantheon.cli.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:70)
 	at tech.pegasys.pantheon.cli.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:26)
 	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
 	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
 	at tech.pegasys.pantheon.cli.PantheonCommand.parse(PantheonCommand.java:545)
 	at tech.pegasys.pantheon.Pantheon.main(Pantheon.java:39)
 Caused by: java.lang.NullPointerException
 	at tech.pegasys.pantheon.crypto.SECP256K1$PrivateKey.store(SECP256K1.java:391)
 	at tech.pegasys.pantheon.controller.KeyPairUtil.loadKeyPair(KeyPairUtil.java:34)
 	at tech.pegasys.pantheon.cli.PantheonControllerBuilder.build(PantheonControllerBuilder.java:93)
 	at tech.pegasys.pantheon.cli.PantheonCommand.buildController(PantheonCommand.java:632)
 	at tech.pegasys.pantheon.cli.PantheonCommand.run(PantheonCommand.java:590)
 	at picocli.CommandLine.execute(CommandLine.java:1160)
 	... 11 more
```

### Steps to Reproduce (Bug)
1. Run node on Linux with the above configuration and command-line options

**Expected behavior:** Node does not crash or produces an informative error message instead of crashing.

**Actual behavior:** Node crashed with a NullPtrException

**Frequency:** 100% of the time.

### Versions (Add all that apply)
* Software version: 0.9.1
* Java version: openjdk version "1.8.0_191"
* OS Name & Version: Ubuntu 16.04.5 LTS
* Kernel Version: Linux 2cd1860584b8 4.9.125-linuxkit
* Virtual Machine software & version: N/A
* Docker Version: 18.09.1
* Cloud VM, type, size: N/A

**Comment by shemnon** [comment]
Quick workaround: don't use a root directory for data.  Try `data-path="/pantheon/data"`

**Comment by etscrivner** [comment]
@shemnon That fixed it. Looks like actually `data-path=""` ended up in the config. My guess is it would still be preferable to handle that edge case.

Appreciate the quick response 🙏
